name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY_NAME: csi-s3
  IMAGE_NAME: csi-s3

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set IMAGE_TAG env
      # GITHUB_REF value: refs/heads/v*
      run: echo "VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Show available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push to GitHub Container Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest


