name: Release

on:
  push:
    tags:
    - "v*"

env:
  REGISTRY_NAME: csi-s3
  IMAGE_NAME: csi-s3

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set IMAGE_TAG env
      # GITHUB_REF value: refs/heads/v*
      run: echo "VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Show available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: Build and publish a Docker image for ${{ github.repository }}
      uses: macbre/push-to-ghcr@master
      with:
        image_name: ${{ github.repository }}  # it will be lowercased internally
        github_token: ${{ secrets.GITHUB_TOKEN }}


